baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"
disqusShortname = "http-applegreengrape-com"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Pingzhou | 平舟"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  showMenuItems = 3
  # showReadingTime = "false"
  # Default theme "light" or "dark"
  defaultTheme = "light"
  googlefonts = ["Droid Sans", "Fira Mono"]
  fontbody = 'Droid Sans'
  fontcode = 'Fira Mono'
  
  

[languages]
  [languages.en]
    title = "Cloud | DevOps | Data | Travel | Exhibition | Shows"
    subtitle = "Pingzhou | 平舟 ⛵️"
    keywords = "Cloud | DevOps | Data | Travel | Exhibition | Shows"
    copyright = ""
    menuMore = "Show more"
    writtenBy = "by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "Pingzhou | 平舟 ⛵️"
      logoHomeLink = "/about"

	# You can create a language based menu
    [languages.en.menu]
       [[languages.en.menu.main]]
        identifier = "Home"
        name = "Home"
        url = "/"

      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      
      [[languages.en.menu.main]]
        identifier = "Archive"
        name = "Posts"
        url = "/archive"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "post"
    name       = "Post"
    url        = "/post"
  [[menu.main]]
    identifier = "Archive"
    name       = "Archive"
    url        = "/archive"